### ISSUE TITLE
编译老是报错，麻烦ga大帮忙看看

### ISSUE THREAD

**Issue by ledewrt** [garypang13/Actions-OpenWrt-Snapshot#1]
package/Makefile:111: recipe for target 'package/boot/grub2/grub2/host/compile' failed
make[2]: *** [package/boot/grub2/grub2/host/compile] Error 2
make[2]: Leaving directory '/home/runner/work/ledeci/ledeci/lede'
make[1]: *** [/home/runner/work/ledeci/ledeci/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
package/Makefile:107: recipe for target '/home/runner/work/ledeci/ledeci/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make: *** [world] Error 2

昨晚看你代码，你添加了CONFIG_GRUB_BOOTOPTS="nomodeset" 就编译成功了，但我还是失败了。

**Comment by garypang13** [comment]
我在你仓库中没找到报这个错的action,最新那个action报错是因为fullconenat与kernel 5.4暂时有些不兼容,需要暂时去掉fullconenat才行.

**Comment by ledewrt** [comment]
ok，我也在不停尝试。多谢

**Comment by garypang13** [comment]
已经修复,可以成功编译fullconenat了. @ledewrt

**Comment by ledewrt** [comment]
好的，我看到了。谢谢
